# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-02 00:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='date_update',
            field=models.DateTimeField(auto_now=True, default=datetime.datetime(2016, 6, 2, 0, 58, 24, 176355)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='date_create',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
