# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-06-03 01:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioitem',
            name='status',
            field=models.CharField(default='draft', max_length=50),
        ),
        migrations.AlterField(
            model_name='portfolioitem',
            name='image',
            field=models.ImageField(upload_to='portfolio/'),
        ),
    ]
